config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'accounts#index'
  get 'accounts/:id' => 'accounts#show', as: 'account'
  put 'accounts/:id' => 'accounts#update'
  patch 'accounts/:id' => 'accounts#update'
end

app/models/account.rb
class Account < ApplicationRecord
    before_save :default_values
    def default_values
        self.credits ||= 0
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    
    def index
        @accounts = Account.all
        @account = Account.new
    end
    
    def show
        @account = Account.find(params[:id])
    end
    
    def create
        @account = Account.new(account_params)
        if @account.save
           redirect_to @account 
        else
            render 'index'
        end
    end
    
    def update
        @account = Account.find(params[:id])
        if @account.update(account_params)
            @account.credits += 1
            redirect_to @account
        else
            render 'show'
        end
    end
    
    private
    
        def account_params
           params.require(:account).permit(:name, :credits) 
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<% @accounts.each do |acc| %>
    <p><%= link_to acc.name, account_path(acc) %></p>
<% end %>

app/views/accounts/show.html.erb
Name: <%= @account.name %>
Credits: <%= @account.credits %>
<%= form_for @account do |f| %>
    <%= f.submit "+" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ucg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>